/**
 * AUTO-GENERATED by scripts/sync-signature-media.mjs (+ sync-signature-recaps.mjs)
 * Do not edit by hand. Only exact curated assets appear here.
 */

export type CuratedEventMedia = {
  poster?: string;
  photo1?: string;
  photo2?: string;
  recapVideo?: string;
  recapThumbnail?: string;
};

export const CURATED_EVENT_MEDIA: Record<string, CuratedEventMedia> = {};
