/**
 * AUTO-GENERATED by scripts/sync-signature-media.mjs (+ sync-signature-recaps.mjs)
 * Do not edit by hand. Only exact curated assets appear here.
 */

export type CuratedEventMedia = {
  poster?: string;
  photo1?: string;
  photo2?: string;
  recapVideo?: string;
  recapThumbnail?: string;
};

export const CURATED_EVENT_MEDIA: Record<string, CuratedEventMedia> = {
  "2024": {
    "poster": "/signature-events/2024/taekwondo-games.jpg",
    "recapVideo": "/signature-events/2024/Taekwondo%20Games.mp4",
    "recapThumbnail": "/signature-events/2024/taekwondo-games.jpg"
  },
  "2025": {
    "poster": "/signature-events/2025/sunday-funday.jpg",
    "photo1": "/signature-events/2025/sunday-funday-01.jpg",
    "photo2": "/signature-events/2025/sunday-funday-02.jpg"
  }
};
